Makefile
sort out annoying error message if no files exist in ~/.kubesim for reset target
=> fix: fix reset target when tidying kubesim

terraform/modules/AWS/Bastion/cloud-config.yaml
disable TcpKeepAlive is sshd config and add ClientAliveInterval and ClientAliveCountMax to the config, increased the client timeout to 2 hours
=> Ssh timeout

pkg/simulator/terraform.go
This moves the change detection out of `InitIfNeeded` which is always run before any command which interacts with infrastructure to only run when running `simulator infra create`
=> feat: move detection of SSH and IP

cmd/infra.go, cmd/root.go, cmd/scenario.go, cmd/ssh.go, pkg/simulator/launch.go, pkg/simulator/ssh.go, pkg/simulator/ssh_test.go, pkg/simulator/terraform.go, pkg/simulator/terraform_test.go, pkg/simulator/terraform_vars.go, pkg/simulator/terraform_vars_test.go, simulator.yaml, terraform/deployments/AWS/main.tf, terraform/deployments/AWS/terraform-bundle.hcl, terraform/deployments/AWS/variables.tf, terraform/modules/AWS/Bastion/cloud-config.tf, terraform/modules/AWS/Bastion/cloud-config.yaml, terraform/modules/AWS/Bastion/variables.tf, test/fixtures/noop-tf-dir/settings/bastion.tfvars
This pull request makes it possible to test tags other than "latest" of the attack container.  This means we will be able to make changes to the attack container and infra in a feature branch and work on the branch until completely happy before merging.  The new workflow to make changes to the attack container on a branch will be:
* code
* commit changes on branch
* `cd attack && CONTAINER_TAG=super-cool-feature make docker-push` to push the tagged attack container
* `cd .. && make run` to run the launch container
* `simulator infra create --attack-container-tag=super-cool-feature`
**Implementation notes**
This pull request adds a new tf var called "attack_container_tag".  The var is threaded through from the deployment to the bastion and is then templated into the cloud-config to pull …
=> Attack container tag selection

.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md, .github/ISSUE_TEMPLATE/config.yml, README.md
Feat: added feature request template, disabled access to blank template, highlighted in issue #76 
Presently there is not template for a feature request so a blank template must be selected
When you raise an issue you will be presented with 2 templates to use, Issue and Feature Request.  No other options are available - blank template denied.
=> Feature request template

terraform/deployments/AWS/main.tf, terraform/deployments/AWS/providers.tf
Fixes #90 by adding a `terraform_remote_state` data source to the provisioner and inserting this value to the default tags map used by the other tf modules.
=> feat(infra): tag AWS resources with the simulator bucket name

Makefile
Mount the terraform and simulation-script directories in `make run` so they can be edited and the changes reflected in the container without needing to re build it.
Due to the way we use TF a read-only mount cannot be used with /terraform. Future work should bypass this limitation.
Fixes #100
=> feat: mount working dirs for make run

Makefile
Fix bug introduced by #110 and validate aws requirements before running `make docker-test` or `make release`.
Should alleviate #67 but will require testing by issuer of the bug.
=> fix(make): validate aws requirements before release or build

Makefile, kubesim
Fixes #78 By changing the mount path used to store SSH keys to `${HOME}/.kubesim` to keep user SSH keys of the container and store all kubesim related files in one place.
=> feat: change ssh mount path

terraform/deployments/AWS/main.tf, terraform/deployments/AWS/providers.tf
Reverts #96  and re-opens #90 as the current implementation is preventing `simulator infra create` when using a new S3 bucket with no tf state.
=> fix(tf): revert #96 as it was preventing tf init for new state

attack/scripts/bashrc, simulation-scripts/scenario/network-hammer-and-anvil/challenge.txt, simulation-scripts/scenario/network-hammer-and-anvil/tasks.yaml
Minor text fixes plus disable strict host key checking for the `attack_node` and `attack_master` functions in the attack container.
=> fix(scen): minor hints update and do not check keys for attack ssh functions

attack/scripts/bashrc, simulation-scripts/scenario/node-shock-tactics/challenge.txt, terraform/deployments/AWS/main.tf, terraform/modules/AWS/Bastion/cloud-config.tf, terraform/modules/AWS/Bastion/cloud-config.yaml, terraform/modules/AWS/Bastion/variables.tf, terraform/modules/AWS/InternalNode/internal-config.tf, terraform/modules/AWS/InternalNode/internal-config.yaml, terraform/modules/AWS/InternalNode/main.tf, terraform/modules/AWS/InternalNode/variables.tf, terraform/modules/AWS/Kubernetes/master-cloud-config.yaml, test/smoke.expect
Updates the internal node config to have kubectl access to the cluster. Also plumbs the internal node into the bastion and attack container config so it can be accessed trivially from the container. 
Updates the language in the attack container to be less aggressive.
Fixes #73
=> feat(tf): add kubectl config to internal node and update attack helpers

simulation-scripts/perturb.sh
Start of refactoring :)
Remove IS_TEST_ONLY variable as unused by simulator and is of limited use as presently implemented
=> Removed unused IS_TEST_ONLY variable and various test

pkg/simulator/launch.go, simulation-scripts/perturb.sh
Reduce the log output for the expected errors when a user attempts to perturb the same cluster twice.
Fixes #123
=> fix(go+peturb): reduce log output for expected double perturb errors

attack/scripts/bashrc
Very small PR to make the text in the attack container readable for light terminal themes.
Fixes #49
=> fix(attack): update colours in attack container for light terminals

Dockerfile, pkg/simulator/perturb.go, pkg/simulator/perturb_test.go, simulation-scripts/perturb.sh, simulation-scripts/scenario/etcd-inverted-wedge/master.sh, simulation-scripts/scenario/master-encirclement/master.sh, simulation-scripts/scenario/node-amphibious-operations/workers-every.sh, simulation-scripts/scenario/policy-fire-support/workers-every.sh, simulation-scripts/scenario/secret-high-ground/workers-every.sh, simulation-scripts/test-func.sh
Large refactor of perturb to hide extraneous `stdout` and `stderr` output.  Changes of note include:
* `warnings` are mostly replaced with `info`s so users don't see red text during normal operation.
* `info` and `success` no longer redirect to `stderr` so output at the correct time in the script instead of sitting in `stderr` until script completion.
* `info` outputs in blue for use across light and dark terminals.
* The `find_scenario` function is brought into the script and fixed to function properly. 
* `test_funcs.sh` is deprecated and commented out as no functions in there are being used.
* Since `found_scenario` is now functional, a minor change was made to replace the `lock_perturb` functions with more granular functionality. 
* Scenario challenge hashes are stored on the cluster …
=> Perturb refactor to hide output

cmd/logger.go
=> feat(go): Change timestamp from Epoc to ISO0860 for human readability

cmd/infra.go, pkg/simulator/terraform.go, pkg/simulator/terraform_test.go, pkg/simulator/terraform_vars.go, pkg/simulator/terraform_vars_test.go, terraform/deployments/AWS/main.tf, terraform/deployments/AWS/providers.tf, terraform/deployments/AWS/terraform.tfvars, terraform/deployments/AWS/variables.tf
This PR does the following:
- removes write to providers.tf, instead consumes bucket flag at terraform init
- removes write to terraform.tfvars, instead inserts into bastion.tfvars
- adjusts tests for new arguments
This is first steps for making terraform mount into launch container read-only
=> Providerstf

simulation-scripts/perturb.sh
Perturb is currently redirecting the scripts to run on the remote hosts to logs rather than ssh. This change fixes that and moves log cleanup to be the last thing perturb does.
=> fix: pertub logging for scenario output

simulation-scripts/perturb.sh
At the moment perturb will error if it tries to clean up script log files that do not exist. This is a bug as not all scenarios use scripts so will not produce these files. This PR fixes that behaviour.
=> fix(perturb): clean up .kubesim files correctly

attack/scripts/bashrc, simulation-scripts/perturb.sh, simulation-scripts/scenario/container-ambush/tasks.yaml, simulation-scripts/scenario/container-defeat-in-detail/tasks.yaml, simulation-scripts/scenario/container-phalanx-formation/tasks.yaml, simulation-scripts/scenario/etcd-inverted-wedge/tasks.yaml, simulation-scripts/scenario/master-encirclement/tasks.yaml, simulation-scripts/scenario/master-shell-scrape/tasks.yaml, simulation-scripts/scenario/network-feint/tasks.yaml, simulation-scripts/scenario/network-hammer-and-anvil/tasks.yaml, simulation-scripts/scenario/network-hedgehog-defence/challenge.txt, simulation-scripts/scenario/network-hedgehog-defence/tasks.yaml, simulation-scripts/scenario/network-swarming/tasks.yaml, simulation-scripts/scenario/node-amphibious-operations/tasks.yaml, simulation-scripts/scenario/node-raiding/challenge.txt, simulation-scripts/scenario/node-raiding/tasks.yaml, simulation-scripts/scenario/node-shock-tactics/tasks.yaml, simulation-scripts/scenario/noop/tasks.yaml, simulation-scripts/scenario/policy-echelon-formation/challenge.txt, simulation-scripts/scenario/policy-echelon-formation/tasks.yaml, simulation-scripts/scenario/policy-fire-support/tasks.yaml, simulation-scripts/scenario/policy-force-dispersal/tasks.yaml, simulation-scripts/scenario/policy-vertical-envelopment/challenge.txt, simulation-scripts/scenario/policy-vertical-envelopment/tasks.yaml, simulation-scripts/scenario/rbac-contact-drill/tasks.yaml, simulation-scripts/scenario/rbac-flanking-maneuver/tasks.yaml, simulation-scripts/scenario/rbac-sangar/tasks.yaml, simulation-scripts/scenario/rbac-shoot-and-scoot/tasks.yaml, simulation-scripts/scenario/secret-high-ground/tasks.yaml, simulation-scripts/scenario/secret-tank-desant/tasks.yaml
Add starting point functionality for pods. The format of the `tasks.yaml` was changed slightly to remove `-` from key names as these needed to be escaped when manipulating the yaml as json.
Perturb ended up going through `shfmt` so there are a lot of non functional formatting changes in there. The functional changes are in the new `template_tasks` function.
Resolves #180
=> Pod starting point

Makefile
Makes the `dep` target of the `Makefile` non `.PHONY` so that it will only run if the `go.mod` file changes. 
**Steps to test**
1. run `make docker-test`
2. Make a trivial edit to a go file (eg change a comment)
3. re-run `make docker-test`
**Expected results**
On the second run of `make docker-test` the go modules do not get downloaded again
=> build: only rerun make dep if go.mod changes

launch-files/launch-entrypoint.sh
This is needed in case an empty temporary directory is passed to `make run`:
```
BUCKET=some-entropic-bucket; KUBE_SIM_TMP="/tmp/kubesim-${BUCKET}"; make run
```
=> fix: ensure ~/.kubesim/simulator.yaml exists

Dockerfile, pkg/simulator/terraform_vars.go, pkg/simulator/terraform_vars_test.go, pkg/util/util_test.go, terraform/deployments/AWS/terraform-bundle.hcl, test/fixtures/tf-dir-with-settings/settings/bastion.tfVars, test/fixtures/tf-dir-with-settings/settings/providers.tf
This PR fixes some issues I had while building and running tests on my box:
* Fixes home path for OSX
* Fixes failed test although I am not 100% sure about `EnsureLatestTfVarsFile` as doc + test and implementation do not match
* Upgrade terraform version as docker build failed with version incompatibility
Some other minor changes based on personal preferences:
* Replaced some `assert.Nil(t, err, "Got an error")` with `require.NoError(t, err)` -> more readable + acts like fatal.
* Flipped some arguments in `assert.Equal(t, expected, actual)` for correct output
=> Fix tests  - OSX

Dockerfile, Makefile
This PR only adds the needed golang files to the golang layer, to make feedback faster when adjusting scripts and other parts of the codebase
=> fix(build): only add needed  files for golang build

Makefile, attack/Makefile
This fixes the release process to ensure an attack container tag is also always pushed with the same version as the launch container and the git release tag.
This has been tested with:
```
cd attack
RELEASE_TAG=v0.5.0 make release
```
and [there is now a `v0.5.0` tag](https://hub.docker.com/layers/controlplane/simulator-attack/v0.5.0/images/sha256-6bc660a5c8d32628ce18258602b1b05d0b58b365f957a4620da173926b72fa01) for the `simulator-attack` container which corresponds to the released `v0.5.0` tag for the launch container and git release.
Future releases will do this automatically when this is merged
=> build(attack): create release target for attack

CONTRIBUTING.md, Makefile, attack/Makefile, cmd/infra.go, cmd/root.go, pkg/simulator/simulator.go, pkg/simulator/terraform.go, pkg/simulator/terraform_vars.go, pkg/simulator/terraform_vars_test.go, terraform/deployments/AWS/main.tf, terraform/deployments/AWS/variables.tf, terraform/modules/AWS/Bastion/cloud-config.tf, terraform/modules/AWS/Bastion/cloud-config.yaml, terraform/modules/AWS/Bastion/goss-template.tf, terraform/modules/AWS/Bastion/goss.yaml, terraform/modules/AWS/Bastion/variables.tf, test/fixtures/noop-tf-dir/settings/bastion.tfvars
This allows anyone to create a tagged version of the attack container in their own docker hub account and then configure their simulator infra to use it.  I have pushed a version tagged `latest` to my dockerhub at `raoulmillais/simulator-attack`.
* checkout this branch
* `make run`
* `simulator infra create --attack-container-repo=raoulmillais/simulator-attack`
* `ssh -F ~/.ssh/cp_simulator_config bastion`
* check the `/home/ubuntu/.bash_login` file invokes docker with the correct repository
* `cd attack`
* `DOCKER_HUB_ORG=<dockerhub-user> CONTAINER_TAG=super-cool-feature make docker-push`
* `cd .. && make run` to run the launch container
* `simulator infra create --attack-container-tag=super-cool-feature --attack-container-repo=<dockerhub-user>/simulator-attack`
=> Attack container docker repository configuration flag

cmd/config.go, cmd/infra.go, cmd/init.go, cmd/logger.go, cmd/root.go, cmd/scenario.go, cmd/ssh.go, cmd/version.go, go.mod, go.sum, pkg/simulator/launch.go, pkg/simulator/remote_state.go, pkg/simulator/simulator.go, pkg/simulator/ssh.go, pkg/simulator/ssh_test.go, pkg/simulator/terraform.go, pkg/simulator/terraform_test.go
This is the first step in addressing the logging technical debt.  This PR migrates away from zap which is designed with microservices in mind, doesn't support pluggable transports and has weak support for [structured logging](https://stackify.com/what-is-structured-logging-and-why-developers-need-it/).
The new implementation uses [logrus](https://github.com/sirupsen/logrus) which is the most commonly used logging framework for Golang CLI apps (docker / runc etc use it).
In all places where we were previously using formatted strings for log messages, I have replaced the message  with a static string and added structured logging fields instead.
I also standardised the logging messages in some places for greater consistency.  There should be negligable impact to the end user.
This will …
=> refactor(simulator): replace zap with logrus

simulation-scripts/scenario/container-defeat-in-detail/challenge.txt, simulation-scripts/scenario/container-phalanx-formation/challenge.txt, simulation-scripts/scenario/etcd-inverted-wedge/challenge.txt, simulation-scripts/scenario/master-encirclement/challenge.txt, simulation-scripts/scenario/master-shell-scrape/challenge.txt, simulation-scripts/scenario/network-hedgehog-defence/challenge.txt, simulation-scripts/scenario/policy-fire-support/challenge.txt, simulation-scripts/scenario/policy-force-dispersal/challenge.txt, simulation-scripts/scenario/rbac-contact-drill/challenge.txt, simulation-scripts/scenario/rbac-sangar/challenge.txt, simulation-scripts/scenario/secret-high-ground/challenge.txt, simulation-scripts/scenario/secret-tank-desant/challenge.txt
This tidying and ordering of the scenarios came from implementing #207. It is partially to create clearer tasks for completion criteria and partially general reformatting for a more easily digestible structure.
=> feat: tidy up for the completion criteria

simulation-scripts/scenario/container-ambush/tasks.yaml, simulation-scripts/scenario/container-defeat-in-detail/tasks.yaml, simulation-scripts/scenario/container-phalanx-formation/tasks.yaml, simulation-scripts/scenario/etcd-inverted-wedge/tasks.yaml, simulation-scripts/scenario/master-encirclement/tasks.yaml, simulation-scripts/scenario/master-shell-scrape/tasks.yaml, simulation-scripts/scenario/network-feint/tasks.yaml, simulation-scripts/scenario/network-hammer-and-anvil/tasks.yaml, simulation-scripts/scenario/network-hedgehog-defence/tasks.yaml, simulation-scripts/scenario/network-swarming/tasks.yaml, simulation-scripts/scenario/node-amphibious-operations/tasks.yaml, simulation-scripts/scenario/node-raiding/tasks.yaml, simulation-scripts/scenario/node-shock-tactics/tasks.yaml, simulation-scripts/scenario/noop/tasks.yaml, simulation-scripts/scenario/policy-echelon-formation/tasks.yaml, simulation-scripts/scenario/policy-fire-support/tasks.yaml, simulation-scripts/scenario/policy-force-dispersal/tasks.yaml, simulation-scripts/scenario/policy-vertical-envelopment/tasks.yaml, simulation-scripts/scenario/rbac-contact-drill/tasks.yaml, simulation-scripts/scenario/rbac-flanking-maneuver/tasks.yaml, simulation-scripts/scenario/rbac-sangar/tasks.yaml, simulation-scripts/scenario/rbac-shoot-and-scoot/tasks.yaml, simulation-scripts/scenario/secret-high-ground/tasks.yaml, simulation-scripts/scenario/secret-tank-desant/tasks.yaml, simulation-scripts/tools/add-category-and-difficulty.sh
Add new fields to the tasks.yaml to document the category and difficulty of each scenario.
Resolves #208, resolves #210
=> feat: add categories and difficulties to scenarios

terraform/modules/AWS/Bastion/cloud-config.yaml
Bug fix
#234 
When exiting from attack container you are now returned to launch container
=> fix: added logout to .bash_login

Makefile, test/infra.test
The `~/.kubesim` folder is not needed when running the tests and it is a pain to arrange for it be there when running in jenkins.  This will fix the jenkins build
=> Don't mount kubesim folder for tests

cmd/infra.go, cmd/root.go, pkg/simulator/simulator.go, pkg/simulator/terraform.go, pkg/simulator/terraform_vars.go, pkg/simulator/terraform_vars_test.go, terraform/deployments/AWS/variables.tf, terraform/modules/AWS/SecurityGroups/main.tf, terraform/modules/AWS/SecurityGroups/variables.tf
Users can now specify CIDRs to be added to the bastion security group with the `--extra-cidrs` flag.
Resolves #164
=> feat: allow extra ips to be added to the bastion sg

attack/scripts/bashrc, docs/tasks-yaml-format.md, simulation-scripts/perturb.sh
Allow users to specify `podHost` and `containerName` in the `tasks.yaml` `startingPoint`. This will allow scenarios to start in multi-container pods and in pods on a specific node.
Resolves #227 
Resolves #218
=> feat: allow specific container and pod host starts

pkg/util/util.go, pkg/util/util_test.go
First of all, I want to provide my deep respect for this project. It is a fantastic project. 
Bug fix
Fail to create `.kubesim/settings/bastion.tfvars` at first time.
Create `.kubesim/settings` dir before create `./kubesim/settings/bastion.tfvars`
No
=> fix: create parent directory before create file in OverwriteFile

Makefile, attack/Makefile, kubesim
Also push to `latest` in Docker when doing a release. This will ensure users will use the latest version of the container when running in Docker without setting a tag.
Also includes a minor volume mount fix for the `kubesim` script.
=> Push to Latest on Release

Dockerfile, pkg/simulator/terraform.go, pkg/simulator/terraform_test.go
Fixes #238 by setting `-compact-warnings` for terraform `apply` and `plan` commands as well as setting `DISABLE_CHECKPOINT` in the launch container.
=> feat: reduce the checks and output of terraform

Dockerfile, terraform/deployments/AWS/main.tf, terraform/deployments/AWS/output.tf, terraform/deployments/AWS/providers.tf, terraform/deployments/AWS/terraform-bundle.hcl, terraform/deployments/AWS/variables.tf, terraform/deployments/AWS/versions.tf, terraform/modules/AWS/Ami/versions.tf, terraform/modules/AWS/Bastion/versions.tf, terraform/modules/AWS/InternalHost/versions.tf, terraform/modules/AWS/Kubernetes/versions.tf, terraform/modules/AWS/Networking/versions.tf, terraform/modules/AWS/S3Storage/versions.tf, terraform/modules/AWS/SecurityGroups/versions.tf, terraform/modules/AWS/SshKey/versions.tf, test/fixtures/tf-help.txt
=> feat: upgrade to terraform 13

README.md, docs/create-scenario.md, docs/tasks-yaml-format.md
adding doc about scenario creation
=> doc: create scenario

Dockerfile.dev, cmd/container/main.go, cmd/simulator/main.go, core/aws/buckets.go, core/aws/env.go, core/tools/ansible.go, core/tools/runner.go, core/tools/terraform.go, docs/cli.md, docs/container-images.md, docs/player-guide.md, internal/cli/bucket.go, internal/cli/config.go, internal/cli/simulator.go, internal/config/config.go, internal/docker/docker.go, internal/logging/factory.go, scenarios/scenarios.go
=> Use OS default config dirs + minor fixes

.github/workflows/build.yaml, .trivy-config/.trivyignore
- fix build fails due to golangci-lint using the latest version of Go instead of the one in the go.mod file
- Add exception for the CVE in the packer binary that hasn't been fixed upstream yet
=> fix(build): linter read Go version from go.mod

terraform/modules/ssh-config/templates/ssh_config
having ssh ForwardAgent on imposes a security risk. It is not necessary in this use-case and will perfectly work without ForwardAgent in the ssh_config.
fixes: #396
=> fix(terraform): remove ForwardAgent on from ssh_client config
