controlplaneio/simulator

simulation-scripts/perturb.sh
fixed redirection issue is file already exists, caused by noclobber setting.
=> fix: fixed get_pods functions 

terraform/README.md, terraform/deployments/AWS/README-auto.md, terraform/deployments/AWS/main.tf, terraform/deployments/AWS/output.tf, terraform/modules/AWS/InternalNode/README-auto.md, terraform/modules/AWS/InternalNode/internal-config.tf, terraform/modules/AWS/InternalNode/internal-config.yaml, terraform/modules/AWS/InternalNode/main.tf, terraform/modules/AWS/InternalNode/output.tf, terraform/modules/AWS/InternalNode/variables.tf
Added additional node to kubernetes subnet, which is not part of the subnet.
Private ip addresses exposed as:
module.InternalNode.InternalNodePrivateIp
=> Terraform additional node

README.md, doc-templates/README.template.md
=> doc: updates to README

README.md, doc-templates/README.template.md
Added details on:
- start_task
- next_hint
- show_hints
Split CLI Usage into logical sections.  General additional tidy up.
=> Added hint/task commands detail to README

attack/scripts/bashrc, terraform/modules/AWS/Bastion/goss-template.tf, terraform/modules/AWS/Bastion/goss.yaml, terraform/modules/AWS/Bastion/test.tf
* Templates the goss.yaml file so that we ensure that the correct tag of the attack container is tested
* Ensures that the tests rerun if you specify a different attack container tag
* Fixes the whitespace in the attack welcome message
* Fixes the welcome message counts of masters and nodes
=> Attack container welcome message

simulation-scripts/scenario/container-ambush/challenge.txt, simulation-scripts/scenario/container-ambush/tasks.yaml, simulation-scripts/scenario/container-defeat-in-detail/challenge.txt, simulation-scripts/scenario/container-defeat-in-detail/tasks.yaml, simulation-scripts/scenario/etcd-inverted-wedge/challenge.txt, simulation-scripts/scenario/master-bait-and-bleed/challenge.txt, simulation-scripts/scenario/network-feint/challenge.txt, simulation-scripts/scenario/network-hammer-and-anvil/challenge.txt, simulation-scripts/scenario/network-hedgehog-defence/challenge.txt, simulation-scripts/scenario/network-swarming/challenge.txt, simulation-scripts/scenario/node-amphibious-operations/challenge.txt, simulation-scripts/scenario/node-raiding/challenge.txt, simulation-scripts/scenario/node-shock-tactics/challenge.txt, simulation-scripts/scenario/policy-echelon-formation/challenge.txt, simulation-scripts/scenario/policy-fire-support/challenge.txt, simulation-scripts/scenario/policy-force-dispersal/challenge.txt, simulation-scripts/scenario/policy-vertical-envelopment/challenge.txt, simulation-scripts/scenario/rbac-contact-drill/challenge.txt, simulation-scripts/scenario/rbac-flanking-maneuver/challenge.txt, simulation-scripts/scenario/rbac-sangar/challenge.txt, simulation-scripts/scenario/rbac-shoot-and-scoot/challenge.txt, simulation-scripts/scenario/secret-high-ground/challenge.txt, simulation-scripts/scenario/secret-tank-desant/challenge.txt
adding starting points to the challenge texts.
=> feat: add starting points

simulation-scripts/scenario/container-ambush/apply/scenario.yaml, simulation-scripts/scenario/etcd-inverted-wedge/apply/scenario.yaml, simulation-scripts/scenario/node-amphibious-operations/apply/scenario.yaml, simulation-scripts/scenario/node-amphibious-operations/challenge.txt, simulation-scripts/scenario/node-amphibious-operations/workers-every.sh, simulation-scripts/scenario/rbac-sangar/tasks.yaml
Some more text fixes for scenarios.
=> Task fixes

README.md, docs/vision-statement.md
Doc addition.  Added Vision Statement document, updated README to with link to this.
This is a proxy PR as Jon Meadows having issues with GH atm
=> Vision statement

simulation-scripts/scenario/container-ambush/tasks.yaml, simulation-scripts/scenario/container-defeat-in-detail/tasks.yaml, simulation-scripts/scenario/container-phalanx-formation/tasks.yaml, simulation-scripts/scenario/etcd-inverted-wedge/tasks.yaml, simulation-scripts/scenario/master-bait-and-bleed/tasks.yaml, simulation-scripts/scenario/master-encirclement/tasks.yaml, simulation-scripts/scenario/network-feint/tasks.yaml, simulation-scripts/scenario/network-hammer-and-anvil/tasks.yaml, simulation-scripts/scenario/network-hedgehog-defence/tasks.yaml, simulation-scripts/scenario/network-swarming/tasks.yaml, simulation-scripts/scenario/node-amphibious-operations/tasks.yaml, simulation-scripts/scenario/node-raiding/tasks.yaml, simulation-scripts/scenario/node-shock-tactics/tasks.yaml, simulation-scripts/scenario/policy-echelon-formation/tasks.yaml, simulation-scripts/scenario/policy-fire-support/tasks.yaml, simulation-scripts/scenario/policy-force-dispersal/tasks.yaml, simulation-scripts/scenario/policy-vertical-envelopment/tasks.yaml, simulation-scripts/scenario/rbac-contact-drill/tasks.yaml, simulation-scripts/scenario/rbac-flanking-maneuver/tasks.yaml, simulation-scripts/scenario/rbac-sangar/tasks.yaml, simulation-scripts/scenario/rbac-shoot-and-scoot/tasks.yaml, simulation-scripts/scenario/secret-high-ground/tasks.yaml, simulation-scripts/scenario/secret-tank-desant/tasks.yaml
- All the starting points fall into four categories with different configurations:
1. Pod: [name: "", namespace: ""]
2. Worker: [as_root: true]
3. Master: [as_root: true]
4. Outside: [network_access: true, kubectl_access: false]
=> Standardise Starting Points

docs/tasks-yaml-format.md, simulation-scripts/scenario/container-ambush/tasks.yaml, simulation-scripts/scenario/container-defeat-in-detail/tasks.yaml, simulation-scripts/scenario/container-phalanx-formation/tasks.yaml, simulation-scripts/scenario/etcd-inverted-wedge/tasks.yaml, simulation-scripts/scenario/master-bait-and-bleed/tasks.yaml, simulation-scripts/scenario/master-encirclement/tasks.yaml, simulation-scripts/scenario/network-feint/tasks.yaml, simulation-scripts/scenario/network-hammer-and-anvil/tasks.yaml, simulation-scripts/scenario/network-hedgehog-defence/tasks.yaml, simulation-scripts/scenario/network-swarming/tasks.yaml, simulation-scripts/scenario/node-amphibious-operations/tasks.yaml, simulation-scripts/scenario/node-raiding/tasks.yaml, simulation-scripts/scenario/node-shock-tactics/tasks.yaml, simulation-scripts/scenario/policy-echelon-formation/tasks.yaml, simulation-scripts/scenario/policy-fire-support/tasks.yaml, simulation-scripts/scenario/policy-force-dispersal/tasks.yaml, simulation-scripts/scenario/policy-vertical-envelopment/tasks.yaml, simulation-scripts/scenario/rbac-contact-drill/tasks.yaml, simulation-scripts/scenario/rbac-flanking-maneuver/tasks.yaml, simulation-scripts/scenario/rbac-sangar/tasks.yaml, simulation-scripts/scenario/rbac-shoot-and-scoot/tasks.yaml, simulation-scripts/scenario/secret-high-ground/tasks.yaml, simulation-scripts/scenario/secret-tank-desant/tasks.yaml
=> Reformat to YAML.

CODEOWNERS, Makefile
- Added @abdullahgarcia to CODEOWNERS file.
- Corrected the Makefile such that if the pwd outcome contains spaces, it handles them correctly.
=> Minor Corrections

docs/tasks-yaml-format.md, simulation-scripts/scenario/container-ambush/tasks.yaml, simulation-scripts/scenario/container-defeat-in-detail/tasks.yaml, simulation-scripts/scenario/container-phalanx-formation/tasks.yaml, simulation-scripts/scenario/etcd-inverted-wedge/tasks.yaml, simulation-scripts/scenario/master-bait-and-bleed/tasks.yaml, simulation-scripts/scenario/master-encirclement/tasks.yaml, simulation-scripts/scenario/network-feint/tasks.yaml, simulation-scripts/scenario/network-hammer-and-anvil/tasks.yaml, simulation-scripts/scenario/network-hedgehog-defence/tasks.yaml, simulation-scripts/scenario/network-swarming/tasks.yaml, simulation-scripts/scenario/node-amphibious-operations/tasks.yaml, simulation-scripts/scenario/node-raiding/tasks.yaml, simulation-scripts/scenario/node-shock-tactics/tasks.yaml, simulation-scripts/scenario/policy-echelon-formation/tasks.yaml, simulation-scripts/scenario/policy-fire-support/tasks.yaml, simulation-scripts/scenario/policy-force-dispersal/tasks.yaml, simulation-scripts/scenario/policy-vertical-envelopment/tasks.yaml, simulation-scripts/scenario/rbac-contact-drill/tasks.yaml, simulation-scripts/scenario/rbac-flanking-maneuver/tasks.yaml, simulation-scripts/scenario/rbac-sangar/tasks.yaml, simulation-scripts/scenario/rbac-shoot-and-scoot/tasks.yaml, simulation-scripts/scenario/secret-high-ground/tasks.yaml, simulation-scripts/scenario/secret-tank-desant/tasks.yaml
=> feat(scen): Added start points for each task in each scenario

pkg/scenario/scenario.go, simulation-scripts/scenario/container-ambush/challenge.txt, simulation-scripts/scenario/container-defeat-in-detail/challenge.txt, simulation-scripts/scenario/container-phalanx-formation/challenge.txt, simulation-scripts/scenario/etcd-inverted-wedge/challenge.txt, simulation-scripts/scenario/master-bait-and-bleed/challenge.txt, simulation-scripts/scenario/master-encirclement/challenge.txt, simulation-scripts/scenario/network-feint/challenge.txt, simulation-scripts/scenario/network-hammer-and-anvil/challenge.txt, simulation-scripts/scenario/network-hedgehog-defence/challenge.txt, simulation-scripts/scenario/network-swarming/challenge.txt, simulation-scripts/scenario/node-amphibious-operations/challenge.txt, simulation-scripts/scenario/node-raiding/challenge.txt, simulation-scripts/scenario/node-shock-tactics/challenge.txt, simulation-scripts/scenario/policy-echelon-formation/challenge.txt, simulation-scripts/scenario/policy-fire-support/challenge.txt, simulation-scripts/scenario/policy-force-dispersal/challenge.txt, simulation-scripts/scenario/policy-vertical-envelopment/challenge.txt, simulation-scripts/scenario/rbac-contact-drill/challenge.txt, simulation-scripts/scenario/rbac-flanking-maneuver/challenge.txt, simulation-scripts/scenario/rbac-sangar/challenge.txt, simulation-scripts/scenario/rbac-shoot-and-scoot/challenge.txt, simulation-scripts/scenario/secret-high-ground/challenge.txt, simulation-scripts/scenario/secret-tank-desant/challenge.txt, simulation-scripts/scenarios.yaml
Initial work for #94. Hoping to get feedback on this first pass before work is done to add a difficulty to each scenario.
=> Task difficulty

docs/create-scenario.md, docs/difficulty.md
A quick doc for setting out some guidelines for the difficulty of tasks. Continues work on #94
=> docs: Added a short .md about task difficulty

Makefile
Fixes #68 
The new output is:
```
setup-dev             Initialise simulation tree with git hooks
devtools-deps         Install devtools dependencies
devtools              Install devtools
test-devtools         Run all the unit tests for the devtools
reset                 Clean up files left over by simulator
validate-reqs         Verify all requirements are met
run                   Run the simulator - the build stage of the container runs all the cli tests
docker-build-nocache  Builds the launch container without the Docker cache
docker-build          Builds the launch container
docker-test           Run the tests
dep                   Install dependencies for other targets
build                 Run golang build for the CLI program
is-in-launch          checks you are running in the …
```
=> docs(make): update the output of make help to be consistent

simulation-scripts/scenario/container-ambush/challenge.txt, simulation-scripts/scenario/container-defeat-in-detail/challenge.txt, simulation-scripts/scenario/container-phalanx-formation/challenge.txt, simulation-scripts/scenario/etcd-inverted-wedge/challenge.txt, simulation-scripts/scenario/master-bait-and-bleed/challenge.txt, simulation-scripts/scenario/master-encirclement/challenge.txt, simulation-scripts/scenario/network-feint/challenge.txt, simulation-scripts/scenario/network-hammer-and-anvil/challenge.txt, simulation-scripts/scenario/network-hedgehog-defence/challenge.txt, simulation-scripts/scenario/network-swarming/challenge.txt, simulation-scripts/scenario/node-amphibious-operations/challenge.txt, simulation-scripts/scenario/node-raiding/challenge.txt, simulation-scripts/scenario/node-shock-tactics/challenge.txt, simulation-scripts/scenario/policy-echelon-formation/challenge.txt, simulation-scripts/scenario/policy-fire-support/challenge.txt, simulation-scripts/scenario/policy-force-dispersal/challenge.txt, simulation-scripts/scenario/policy-vertical-envelopment/challenge.txt, simulation-scripts/scenario/rbac-contact-drill/challenge.txt, simulation-scripts/scenario/rbac-flanking-maneuver/challenge.txt, simulation-scripts/scenario/rbac-sangar/challenge.txt, simulation-scripts/scenario/rbac-shoot-and-scoot/challenge.txt, simulation-scripts/scenario/secret-high-ground/challenge.txt, simulation-scripts/scenario/secret-tank-desant/challenge.txt, simulation-scripts/scenarios.yaml
Add difficulties for each scenario so closing #94. I'd like to leave this open until the 26th so we can gather comments about the level each scenario is rated.
=> feat(scen): add difficulties to the scenarios

docs/vision-statement.md
=> doc: updated

docs/vision-statement.md
=> doc: add controlplane team to VS

simulation-scripts/perturb.sh
Adds feature to ensure that perturb errors if it is run more than once against a cluster, addressing issue #72 
Currently perturb can be run multiple times, leading to unexpected behaviour with scenarios
Adds lock file to master node, verifies if this exists and if so exits with error
This highlights a problem with the simulator handling error exits, an issue has been raised for this.
=> add locking to ensure perturb only run once

cmd/scenario.go
The existing code was printing out additional unnecessary information that was only misleading and visually confusing for the users.
The code has been corrected to output into the system regular messages.
=> Correct scenario list output.

cmd/scenario.go, pkg/scenario/scenario.go, simulation-scripts/scenario/rbac-shoot-and-scoot/apply/scenario.yaml, simulation-scripts/scenario/rbac-shoot-and-scoot/challenge.txt, simulation-scripts/scenario/rbac-shoot-and-scoot/tasks.yaml, simulation-scripts/scenarios.yaml
Descriptions have been added to each scenario and are outputted on `simulator scenario list`. The format of `simulator scenario list` has also been updated to better fit with outputs that are over a line long.
The `rbac-shoot-and-scoot` scenario received a minor update to make it more unique.
=> feat(scen): Add descriptions to each scenario

docs/IP-Detection.md
A small change to add a document describing how simulator determines a users' IP.
Fixes #155 
Fixes #156
=> docs: document ip detection process

CODEOWNERS, Jenkinsfile
=> feat: test new jenkins creds

Jenkinsfile
This reverts commit a65d0c5c2e042e311f277e11590f8b1bf04e0e2b.
=> Revert "feat: test new jenkins creds"

.github/workflows/stale.yml
Minor update to increase the time before issues are closed and add an exemption label.
=> feat(github): update stale timeout and exemptions

attack/scripts/bashrc
Minor change to fix an oversight from #167
=> fix(attack): update env var for internal host ip

Jenkinsfile, test/init.test
Changes jenkins to use new AWS account
=> feat: change AWS account

docs/tasks-yaml-format.md, simulation-scripts/perturb.sh, simulation-scripts/scenario/container-ambush/tasks.yaml, simulation-scripts/scenario/container-defeat-in-detail/tasks.yaml, simulation-scripts/scenario/container-phalanx-formation/tasks.yaml, simulation-scripts/scenario/etcd-inverted-wedge/tasks.yaml, simulation-scripts/scenario/master-encirclement/tasks.yaml, simulation-scripts/scenario/master-shell-scrape/tasks.yaml, simulation-scripts/scenario/network-feint/tasks.yaml, simulation-scripts/scenario/network-hammer-and-anvil/tasks.yaml, simulation-scripts/scenario/network-hedgehog-defence/tasks.yaml, simulation-scripts/scenario/network-swarming/tasks.yaml, simulation-scripts/scenario/node-amphibious-operations/tasks.yaml, simulation-scripts/scenario/node-raiding/tasks.yaml, simulation-scripts/scenario/node-shock-tactics/tasks.yaml, simulation-scripts/scenario/policy-echelon-formation/tasks.yaml, simulation-scripts/scenario/policy-fire-support/tasks.yaml, simulation-scripts/scenario/policy-force-dispersal/tasks.yaml, simulation-scripts/scenario/policy-vertical-envelopment/tasks.yaml, simulation-scripts/scenario/rbac-contact-drill/tasks.yaml, simulation-scripts/scenario/rbac-flanking-maneuver/tasks.yaml, simulation-scripts/scenario/rbac-sangar/tasks.yaml, simulation-scripts/scenario/rbac-shoot-and-scoot/tasks.yaml, simulation-scripts/scenario/secret-high-ground/tasks.yaml, simulation-scripts/scenario/secret-tank-desant/tasks.yaml, simulation-scripts/tools/add-hint-penalty.sh
Adds a hint penalty for all tasks and a short script to add/set all hint penalty key: values.
Requires #181 to be merged first.
Resolves #170
=> Hint penalty

simulation-scripts/scenario/rbac-sangar/challenge.txt
=> fix: rbac-sanger typos

attack/scripts/bashrc
This clarifies the wording at the start of a scenario
Mis-ordered commands, duplicate `welcome` command reminder
Clearer
No
=> fix: reorder welcome message for clarity

scripts/validate-requirements
Simple typo fix in validate-requirements script that was annoying me
Fixes issue #200
=> fix(validate-requirements) - fix typo in sentance

terraform/deployments/AWS/variables.tf, terraform/modules/AWS/Ami/output.tf, terraform/modules/AWS/Bastion/cloud-config.tf, terraform/modules/AWS/Bastion/goss-template.tf, terraform/modules/AWS/Bastion/main.tf, terraform/modules/AWS/Bastion/output.tf, terraform/modules/AWS/Bastion/test.tf, terraform/modules/AWS/Bastion/variables.tf, terraform/modules/AWS/InternalHost/internal-config.tf, terraform/modules/AWS/InternalHost/main.tf, terraform/modules/AWS/InternalHost/output.tf, terraform/modules/AWS/InternalHost/test.tf, terraform/modules/AWS/InternalHost/variables.tf, terraform/modules/AWS/Kubernetes/main.tf, terraform/modules/AWS/Kubernetes/master-cloud-config.tf, terraform/modules/AWS/Kubernetes/node-cloud-config.tf, terraform/modules/AWS/Kubernetes/output.tf, terraform/modules/AWS/Kubernetes/test.tf, terraform/modules/AWS/Kubernetes/variables.tf, terraform/modules/AWS/Networking/main.tf, terraform/modules/AWS/Networking/output.tf, terraform/modules/AWS/Networking/variables.tf, terraform/modules/AWS/S3Storage/main.tf, terraform/modules/AWS/S3Storage/output.tf, terraform/modules/AWS/S3Storage/variables.tf, terraform/modules/AWS/SecurityGroups/main.tf, terraform/modules/AWS/SecurityGroups/output.tf, terraform/modules/AWS/SecurityGroups/variables.tf, terraform/modules/AWS/SshKey/main.tf, terraform/modules/AWS/SshKey/output.tf
Refactor terraform modules and variables.tf to comform with terraform 0.12 hcl changes
Refer to https://www.terraform.io/upgrade-guides/0-12.html
=> refactor(terraform) - refactor terraform

cmd/scenario.go
This adds the describe option to scenario, i.e. `simulator scenario describe <id>`
=> feat: describe scenario

cmd/scenario.go, pkg/scenario/scenario.go, simulation-scripts/scenarios.yaml
Formats `simulator scenario list` to make it more readable.
Resolves #211
=> feat: format scenarios list into a matrix

docs/tasks-yaml-format.md, simulation-scripts/scenario/container-ambush/tasks.yaml, simulation-scripts/scenario/container-defeat-in-detail/tasks.yaml, simulation-scripts/scenario/container-phalanx-formation/tasks.yaml, simulation-scripts/scenario/etcd-inverted-wedge/tasks.yaml, simulation-scripts/scenario/master-encirclement/tasks.yaml, simulation-scripts/scenario/master-shell-scrape/tasks.yaml, simulation-scripts/scenario/network-feint/tasks.yaml, simulation-scripts/scenario/network-hammer-and-anvil/tasks.yaml, simulation-scripts/scenario/network-hedgehog-defence/tasks.yaml, simulation-scripts/scenario/network-swarming/tasks.yaml, simulation-scripts/scenario/node-amphibious-operations/tasks.yaml, simulation-scripts/scenario/node-raiding/tasks.yaml, simulation-scripts/scenario/node-shock-tactics/tasks.yaml, simulation-scripts/scenario/policy-echelon-formation/tasks.yaml, simulation-scripts/scenario/policy-fire-support/tasks.yaml, simulation-scripts/scenario/policy-force-dispersal/tasks.yaml, simulation-scripts/scenario/policy-vertical-envelopment/tasks.yaml, simulation-scripts/scenario/rbac-contact-drill/tasks.yaml, simulation-scripts/scenario/rbac-flanking-maneuver/tasks.yaml, simulation-scripts/scenario/rbac-sangar/tasks.yaml, simulation-scripts/scenario/rbac-shoot-and-scoot/tasks.yaml, simulation-scripts/scenario/secret-high-ground/tasks.yaml, simulation-scripts/scenario/secret-tank-desant/tasks.yaml
Add clarity to tasks.yaml spec and remove extraneous startingPoint staza from current tasks.yaml.
Resolves #209
=> docs: update tasks.yaml spec

attack/scripts/bashrc
quick tidy of the welcome message
=> fix: clarify welcome message

simulation-scripts/scenario/container-ambush/tasks.yaml, simulation-scripts/scenario/container-defeat-in-detail/tasks.yaml, simulation-scripts/scenario/container-phalanx-formation/tasks.yaml, simulation-scripts/scenario/etcd-inverted-wedge/tasks.yaml, simulation-scripts/scenario/master-encirclement/tasks.yaml, simulation-scripts/scenario/master-shell-scrape/tasks.yaml, simulation-scripts/scenario/network-feint/tasks.yaml, simulation-scripts/scenario/network-hammer-and-anvil/tasks.yaml, simulation-scripts/scenario/network-hedgehog-defence/tasks.yaml, simulation-scripts/scenario/network-swarming/tasks.yaml, simulation-scripts/scenario/node-amphibious-operations/tasks.yaml, simulation-scripts/scenario/node-raiding/tasks.yaml, simulation-scripts/scenario/node-shock-tactics/tasks.yaml, simulation-scripts/scenario/policy-echelon-formation/tasks.yaml, simulation-scripts/scenario/policy-fire-support/tasks.yaml, simulation-scripts/scenario/policy-force-dispersal/tasks.yaml, simulation-scripts/scenario/policy-vertical-envelopment/tasks.yaml, simulation-scripts/scenario/rbac-contact-drill/tasks.yaml, simulation-scripts/scenario/rbac-flanking-maneuver/tasks.yaml, simulation-scripts/scenario/rbac-sangar/tasks.yaml, simulation-scripts/scenario/rbac-shoot-and-scoot/tasks.yaml, simulation-scripts/scenario/secret-high-ground/tasks.yaml, simulation-scripts/scenario/secret-tank-desant/tasks.yaml, simulation-scripts/scenarios.yaml
Fix capitalisation of category names as it was annoying me.
=> chore: minor category capitalisation fix

cmd/infra.go, cmd/root.go, cmd/scenario.go, cmd/ssh.go, docs/IP-Detection.md, pkg/simulator/simulator.go, pkg/simulator/ssh_test.go, pkg/simulator/terraform.go, pkg/simulator/terraform_test.go, simulation-scripts/scenario/node-amphibious-operations/challenge.txt
=> Optional ip check

simulation-scripts/scenario/policy-force-dispersal/challenge.txt, simulation-scripts/scenario/policy-force-dispersal/tasks.yaml
=> fix: pfd scen

Makefile, README.md
Tidy up of the readme and Makefile target descriptions:
This fixes #249 
This fixes #255 
This fixes #171 (was already done by @pi-unnerup )
This fixes #256
=> Readme updates

simulation-scripts/perturb.sh
Remove trailing $ from info outpout
see #258 
Trailing $ no longer  displayed
n/a
n/a
=> fix: removed trail $ from info output

terraform/modules/AWS/Bastion/cloud-config.yaml, terraform/modules/AWS/Kubernetes/master-cloud-config.yaml, terraform/modules/AWS/Kubernetes/node-cloud-config.yaml
Fixes #270 with a minor update to enable the Docker service on the hosts.
=> Enable Docker Service for Goss Tests

kubesim
=> fix: kubesim script quotes and mkdir

CODEOWNERS
@raoulmillais fixing your username in the CODEOWNERS.
=> fix: username for collaborator in CODEOWNERS

pkg/simulator/terraform.go
Ensures that `terraform apply` is only run if `terraform plan` shows changes to the infrastructure
fixes #265
=> feat: isInfraUp

tools/scenario-tools/bin/next_hint.js, tools/scenario-tools/bin/show_hints.js, tools/scenario-tools/lib/tasks.js, tools/scenario-tools/test/fixtures/tasks-no-task.yaml, tools/scenario-tools/test/tasks_test.js
Fixes #230 
I had to also update the conditional error for the `next_hint` and `show_hint` helpers. I think this due to changes in e325d0520a13698b8a93dad61552077e66ccfef4.
=> Error on no Scenario for Task Helpers

terraform/deployments/AWS/providers.tf
Small PR to suppress provider version warnings from terraform.
=> Pin Terraform Provider Versions

simulation-scripts/perturb.sh
=> Improve pod check so jq doesn't error

cmd/infra.go, cmd/root.go, cmd/scenario.go, cmd/ssh.go
fixes #251 
All Commands:
"loglevel"
"config-file"
"state-bucket"
infra
"disable-ip-detection"
"tf-dir"
"tf-vars-dir"
"attack-container-tag"
"github-usernames"
"extra-cidrs"
scenario
"scenarios-dir"
"difficulty"
"category"
ssh
"tf-dir"
"tf-vars-dir"
=> Global to local flags

cmd/infra.go, cmd/scenario.go, cmd/ssh.go, pkg/simulator/ssh_test.go
=> Only ip detect on infra create

cmd/init.go, pkg/simulator/terraform.go
=> Reduce the number of times we Terraform init

attack/scripts/bashrc, terraform/modules/AWS/Bastion/cloud-config.yaml, tools/scenario-tools/test/fixtures/tasks-no-task.yaml
=> Break up the attack container welcome message

attack/scripts/bashrc
=> Check task was set before accessing the cluster

Makefile, README.md
=> Add kubesim to releases

cmd/infra.go, cmd/scenario.go
=> Move CLI Options to Subcommands

Makefile
=> Add merge information to release text

attack/scripts/bashrc
=> Attack container updated to recognise started task

cmd/container/main.go, core/tools/ansible.go, core/tools/packer.go, core/tools/runner.go, core/tools/terraform.go
Allows, runner to log command output and errors to different io.Writers
=> feat: separate logs to STDOUT & STDERR
